name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' 

      - name: Run Unit Tests
        run: go test -v ./tests

      - name: Build Docker Image
        run: |
          docker build -t your-image-name:latest .
          # แทนที่ your-image-name ด้วยชื่อที่คุณต้องการ

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-image-name:latest
