# name: CI

# on:
#   push:
#     branches:
#       - '*'
#   pull_request:
#     branches:
#       - develop

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: '1.20' 

#       - name: Run Unit Tests
#         run: go test -v ./tests

#       - name: Build Docker Image
#         run: |
#           docker build -f docker/prod.Dockerfile -t aeuro7/agdo_test:latest .

#       - name: Push Docker Image
#         run: |
#           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#           docker push aeuro7/agdo_test:latest
